#!/usr/bin/env bash

set -euo pipefail

ACTONCE_ANDROID_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ACTONCE_ROOT="$(cd "${ACTONCE_ANDROID_SCRIPT_DIR}/../.." && pwd)"

export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-${ACTONCE_ROOT}/.cache/android-sdk}"
export ANDROID_HOME="${ANDROID_HOME:-${ANDROID_SDK_ROOT}}"
export ANDROID_AVD_HOME="${ANDROID_AVD_HOME:-${ACTONCE_ROOT}/.cache/android-avd}"

ACTONCE_JAVA_HOME="${ACTONCE_JAVA_HOME:-${ACTONCE_ROOT}/.cache/jdk/Contents/Home}"
if [[ -x "${ACTONCE_JAVA_HOME}/bin/java" ]]; then
  export JAVA_HOME="${JAVA_HOME:-${ACTONCE_JAVA_HOME}}"
fi

export PATH="${JAVA_HOME:+${JAVA_HOME}/bin:}${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:${ANDROID_SDK_ROOT}/platform-tools:${ANDROID_SDK_ROOT}/emulator:${PATH}"
export MIDSCENE_ADB_PATH="${MIDSCENE_ADB_PATH:-${ANDROID_SDK_ROOT}/platform-tools/adb}"

ACTONCE_ANDROID_API="${ACTONCE_ANDROID_API:-35}"
ACTONCE_ANDROID_IMAGE_FLAVOR="${ACTONCE_ANDROID_IMAGE_FLAVOR:-google_apis}"
ACTONCE_AVD_NAME="${ACTONCE_AVD_NAME:-actonce_api35_google_apis}"
ACTONCE_EMULATOR_PORT="${ACTONCE_EMULATOR_PORT:-5554}"
ACTONCE_EMULATOR_GPU="${ACTONCE_EMULATOR_GPU:-swiftshader}"
ACTONCE_ANDROID_SERIAL="${ACTONCE_ANDROID_SERIAL:-emulator-${ACTONCE_EMULATOR_PORT}}"
ACTONCE_DATA_PARTITION_SIZE="${ACTONCE_DATA_PARTITION_SIZE:-536870912}"
ACTONCE_PARTITION_SIZE_MB="${ACTONCE_PARTITION_SIZE_MB:-2048}"

case "$(uname -m)" in
  arm64 | aarch64)
    ACTONCE_ANDROID_ARCH="arm64-v8a"
    ;;
  x86_64 | amd64)
    ACTONCE_ANDROID_ARCH="x86_64"
    ;;
  *)
    echo "Unsupported host architecture: $(uname -m)" >&2
    exit 1
    ;;
esac

ACTONCE_SYSTEM_IMAGE="system-images;android-${ACTONCE_ANDROID_API};${ACTONCE_ANDROID_IMAGE_FLAVOR};${ACTONCE_ANDROID_ARCH}"
export ACTONCE_ROOT ACTONCE_ANDROID_API ACTONCE_ANDROID_ARCH
export ACTONCE_ANDROID_IMAGE_FLAVOR
export ACTONCE_AVD_NAME ACTONCE_EMULATOR_PORT ACTONCE_ANDROID_SERIAL
export ACTONCE_EMULATOR_GPU
export ACTONCE_DATA_PARTITION_SIZE ACTONCE_PARTITION_SIZE_MB ACTONCE_SYSTEM_IMAGE
