#!/usr/bin/env bash

set -euo pipefail

ACTONCE_IOS_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ACTONCE_ROOT="$(cd "${ACTONCE_IOS_SCRIPT_DIR}/../.." && pwd)"

ACTONCE_IOS_DEVICE_NAME="${ACTONCE_IOS_DEVICE_NAME:-ActOnce iPhone 17 Pro}"
ACTONCE_IOS_DEVICE_TYPE="${ACTONCE_IOS_DEVICE_TYPE:-com.apple.CoreSimulator.SimDeviceType.iPhone-17-Pro}"
ACTONCE_IOS_RUNTIME="${ACTONCE_IOS_RUNTIME:-com.apple.CoreSimulator.SimRuntime.iOS-26-5}"
ACTONCE_WDA_HOST="${ACTONCE_WDA_HOST:-127.0.0.1}"
ACTONCE_WDA_PORT="${ACTONCE_WDA_PORT:-8100}"
ACTONCE_WDA_MJPEG_PORT="${ACTONCE_WDA_MJPEG_PORT:-9100}"

export ACTONCE_ROOT ACTONCE_IOS_DEVICE_NAME ACTONCE_IOS_DEVICE_TYPE
export ACTONCE_IOS_RUNTIME ACTONCE_WDA_HOST ACTONCE_WDA_PORT
export ACTONCE_WDA_MJPEG_PORT

